version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - ./:/near_places
    working_dir: /near_places
    command: puma
    ports: 
      - 3000:3000
    depends_on: 
      - db
    environment: 
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10.3-alpine