default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: near_places_development

test:
  <<: *default
  database: near_places_test

production:
  <<: *default
  database: near_places_production